# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  numbers = [1, 2]
  i = 1 
  even_numbers = []
  while i < numbers.length
    numbers << numbers[i] + numbers[i-1]
    if numbers.last == 3524578
      break
    else
      i += 1
    end
  end
  p numbers

  numbers.each do |number|
    if number.even?
      even_numbers << number
    end
  end
  p even_numbers  
  p even_numbers.sum 


